import SASFU
aspirante2=SASFU.Aspirante("1312685560","Daniel","Correa","Daniel@gmail.com","097859433",True,8.02)
aspirante2.cargar_datos()
usuario=input("Ingrese su nombre de usuario:")
contraseña=input("Ingrese su contraseña:")
contraseña_confirm=input("Confirme su contraseña:")
aspirante2.crear_usuario(usuario, contraseña, contraseña_confirm)
usuario=input("Ingrese su nombre de usuario:")
contraseña=input("Ingrese su contraseña:")
aspirante2.iniciar_sesion(usuario, contraseña)
print(aspirante2.nacionalidad())
aspirante2.cerrar_sesion()
